-- Criação do banco de dados
CREATE DATABASE Master_of_tenses;

-- Uso do banco de dados criado
USE Master_of_tenses;

-- Criação da tabela Usuário
CREATE TABLE table_user (
   email VARCHAR(100) PRIMARY KEY,
   user_name VARCHAR(100) NOT NULL,
   user_password VARCHAR(100) NOT NULL,
   register_date DATE NOT NULL,
   verb_register_json JSON
);

-- Criação da tabela VerboEmEstudo
CREATE TABLE user_verb_in_study (
   user_email VARCHAR(100) NOT NULL
   verb_id INT NOT NULL,
   expires DATE NOT NULL,
   stability FLOAT NOT NULL,
   difficult FLOAT NOT NULL,
   repetitions INT NOT NULL,
   lapses INT NOT NULL,
   learning_state INT NOT NULL,
   last_review DATE NOT NULL

   CONSTRAINT fk_user_verb_in_study_user 
      FOREIGN KEY (user_email) 
      REFERENCES table_user(email), 
   CONSTRAINT fk_user_verb_in_study_verb 
      FOREIGN KEY (verb_id) 
      REFERENCES verbs(id), 

);

-- Criação da tabela Verbo
CREATE TABLE verbs (
   definitions TEXT,
   phonetics VARCHAR(100) NOT NULL,
   usageIndex DECIMAL(12,12) NOT NULL,
   infinitive VARCHAR(50) NOT NULL,
   infinitive_audio VARCHAR(100),
                                       
   simple_past VARCHAR(50) NOT NULL,
   simple_past_audio VARCHAR(100),
   simple_past_uk VARCHAR(50),
   simple_past_uk_audio VARCHAR(100),

   participle VARCHAR(50) NOT NULL,
   participle_audio VARCHAR(100),
   participle_uk VARCHAR(50),
   participle_uk_audio VARCHAR(100),
   id int AUTO_INCREMENT,
   
   constraint verb_pk
      primary key (id)
);

-- Dados de testes para a tabela verb

INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/dʉː/', 0.000592348896, 'do', NULL, 'did', NULL, NULL, NULL, 'done', NULL, NULL, NULL, 37);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/kʌm/', 0.000345387909, 'come', NULL, 'came', 'https://api.dictionaryapi.dev/media/pronunciations/en/came-us.mp3', NULL, NULL, 'come', NULL, NULL, NULL, 28);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈbɹɪŋ/', 0.000138817341, 'bring', 'https://api.dictionaryapi.dev/media/pronunciations/en/bring-us.mp3', 'brought', NULL, NULL, NULL, 'brought', NULL, NULL, NULL, 16);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈkɑst/', 0.000134828321, 'cost', 'https://api.dictionaryapi.dev/media/pronunciations/en/cost-us.mp3', 'cost', 'https://api.dictionaryapi.dev/media/pronunciations/en/cost-us.mp3', NULL, NULL, 'cost', 'https://api.dictionaryapi.dev/media/pronunciations/en/cost-us.mp3', NULL, NULL, 29);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/biˈɡɪn/', 0.000103375176, 'begin', 'https://api.dictionaryapi.dev/media/pronunciations/en/begin-us.mp3', 'began', 'https://api.dictionaryapi.dev/media/pronunciations/en/began-us.mp3', NULL, NULL, 'begun', 'https://api.dictionaryapi.dev/media/pronunciations/en/begun-us.mp3', NULL, NULL, 7);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/kʌt/', 0.000094227852, 'cut', 'https://api.dictionaryapi.dev/media/pronunciations/en/cut-us.mp3', 'cut', 'https://api.dictionaryapi.dev/media/pronunciations/en/cut-us.mp3', NULL, NULL, 'cut', 'https://api.dictionaryapi.dev/media/pronunciations/en/cut-us.mp3', NULL, NULL, 32);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɪld/', 0.000076090030, 'build', 'https://api.dictionaryapi.dev/media/pronunciations/en/build-us.mp3', 'built', 'https://api.dictionaryapi.dev/media/pronunciations/en/built-us.mp3', NULL, NULL, 'built', 'https://api.dictionaryapi.dev/media/pronunciations/en/built-us.mp3', NULL, NULL, 18);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/kæt͡ʃ/', 0.000062490606, 'catch', 'https://api.dictionaryapi.dev/media/pronunciations/en/catch-us.mp3', 'caught', NULL, NULL, NULL, 'caught', NULL, NULL, NULL, 24);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bʌɪt/', 0.000050175509, 'bite', 'https://api.dictionaryapi.dev/media/pronunciations/en/bite-us.mp3', 'bit', 'https://api.dictionaryapi.dev/media/pronunciations/en/bit-us.mp3', NULL, NULL, 'bitten', NULL, NULL, NULL, 11);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/baɪnd/', 0.000044428662, 'bind', 'https://api.dictionaryapi.dev/media/pronunciations/en/bind-us.mp3', 'bound', 'https://api.dictionaryapi.dev/media/pronunciations/en/bound-us.mp3', NULL, NULL, 'bound', 'https://api.dictionaryapi.dev/media/pronunciations/en/bound-us.mp3', NULL, NULL, 10);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɹeɪk/', 0.000043001463, 'break', 'https://api.dictionaryapi.dev/media/pronunciations/en/break-us.mp3', 'broke', 'https://api.dictionaryapi.dev/media/pronunciations/en/broke-us.mp3', NULL, NULL, 'broken', 'https://api.dictionaryapi.dev/media/pronunciations/en/broken-us.mp3', NULL, NULL, 14);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɛə(ɹ)/', 0.000042135899, 'bear', 'https://api.dictionaryapi.dev/media/pronunciations/en/bear-us.mp3', 'bore', 'https://api.dictionaryapi.dev/media/pronunciations/en/bore-us.mp3', 'bore', NULL, 'born', 'https://api.dictionaryapi.dev/media/pronunciations/en/born-us.mp3', 'borne', NULL, 5);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/dɹɔː/', 0.000041010064, 'draw', NULL, 'drew', 'https://api.dictionaryapi.dev/media/pronunciations/en/drew-us.mp3', NULL, NULL, 'drawn', 'https://api.dictionaryapi.dev/media/pronunciations/en/drawn-us.mp3', NULL, NULL, 38);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/kæst/', 0.000036379603, 'cast', 'https://api.dictionaryapi.dev/media/pronunciations/en/cast-us.mp3', 'cast', 'https://api.dictionaryapi.dev/media/pronunciations/en/cast-us.mp3', NULL, NULL, 'cast', 'https://api.dictionaryapi.dev/media/pronunciations/en/cast-us.mp3', NULL, NULL, 23);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/t͡ʃuːz/', 0.000033832980, 'choose', NULL, 'chose', NULL, NULL, NULL, 'chosen', NULL, NULL, NULL, 25);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/baɪ/', 0.000031909007, 'buy', 'https://api.dictionaryapi.dev/media/pronunciations/en/buy-us.mp3', 'bought', 'https://api.dictionaryapi.dev/media/pronunciations/en/bought-us.mp3', NULL, NULL, 'bought', 'https://api.dictionaryapi.dev/media/pronunciations/en/bought-us.mp3', NULL, NULL, 22);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɛnd/', 0.000020676448, 'bend', NULL, 'bent', 'https://api.dictionaryapi.dev/media/pronunciations/en/bent-us.mp3', NULL, NULL, 'bent', 'https://api.dictionaryapi.dev/media/pronunciations/en/bent-us.mp3', NULL, NULL, 8);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɜːst/', 0.000019563999, 'burst', 'https://api.dictionaryapi.dev/media/pronunciations/en/burst-us.mp3', 'burst', 'https://api.dictionaryapi.dev/media/pronunciations/en/burst-us.mp3', NULL, NULL, 'burst', 'https://api.dictionaryapi.dev/media/pronunciations/en/burst-us.mp3', NULL, NULL, 20);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɜːn/', 0.000019472893, 'burn', 'https://api.dictionaryapi.dev/media/pronunciations/en/burn-us.mp3', 'burned', 'https://api.dictionaryapi.dev/media/pronunciations/en/burned-us.mp3', 'burnt', NULL, 'burned', 'https://api.dictionaryapi.dev/media/pronunciations/en/burned-us.mp3', 'burnt', NULL, 19);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/biːt/', 0.000019416826, 'beat', 'https://api.dictionaryapi.dev/media/pronunciations/en/beat-us.mp3', 'beat', 'https://api.dictionaryapi.dev/media/pronunciations/en/beat-us.mp3', 'beat', NULL, 'beaten', 'https://api.dictionaryapi.dev/media/pronunciations/en/beaten-us.mp3', 'beat', NULL, 6);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/diːl/', 0.000015180988, 'deal', 'https://api.dictionaryapi.dev/media/pronunciations/en/deal-us.mp3', 'dealt', 'https://api.dictionaryapi.dev/media/pronunciations/en/dealt-us.mp3', NULL, NULL, 'dealt', 'https://api.dictionaryapi.dev/media/pronunciations/en/dealt-us.mp3', NULL, NULL, 34);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈbɛt/', 0.000014126541, 'bet', 'https://api.dictionaryapi.dev/media/pronunciations/en/bet-us.mp3', 'bet', 'https://api.dictionaryapi.dev/media/pronunciations/en/bet-us.mp3', 'betted', NULL, 'bet', 'https://api.dictionaryapi.dev/media/pronunciations/en/bet-us.mp3', 'betted', NULL, 9);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈbɹɑdkæst/', 0.000010673804, 'broadcast', 'https://api.dictionaryapi.dev/media/pronunciations/en/broadcast-us.mp3', 'broadcast', 'https://api.dictionaryapi.dev/media/pronunciations/en/broadcast-us.mp3', 'broadcasted', NULL, 'broadcast', 'https://api.dictionaryapi.dev/media/pronunciations/en/broadcast-us.mp3', 'broadcasted', NULL, 17);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bləʊ/', 0.000009499641, 'blow', 'https://api.dictionaryapi.dev/media/pronunciations/en/blow-us.mp3', 'blew', 'https://api.dictionaryapi.dev/media/pronunciations/en/blew-us.mp3', NULL, NULL, 'blown', 'https://api.dictionaryapi.dev/media/pronunciations/en/blown-us.mp3', NULL, NULL, 13);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/dɪɡ/', 0.000009161734, 'dig', NULL, 'dug', NULL, NULL, NULL, 'dug', NULL, NULL, NULL, 35);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/əˈɹaɪz/', 0.000008158573, 'arise', 'https://api.dictionaryapi.dev/media/pronunciations/en/arise-us.mp3', 'arose', 'https://api.dictionaryapi.dev/media/pronunciations/en/arose-us.mp3', NULL, NULL, 'arisen', 'https://api.dictionaryapi.dev/media/pronunciations/en/arisen-us.mp3', NULL, NULL, 1);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/əˈɹaɪz/', 0.000008158573, 'arise', 'https://api.dictionaryapi.dev/media/pronunciations/en/arise-us.mp3', 'arose', 'https://api.dictionaryapi.dev/media/pronunciations/en/arose-us.mp3', NULL, NULL, 'arisen', 'https://api.dictionaryapi.dev/media/pronunciations/en/arisen-us.mp3', NULL, NULL, 3);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/dɹiːm/', 0.000007018385, 'dream', 'https://api.dictionaryapi.dev/media/pronunciations/en/dream-us.mp3', 'dreamed', 'https://api.dictionaryapi.dev/media/pronunciations/en/dreamed-us.mp3', 'dreamt', NULL, 'dreamed', 'https://api.dictionaryapi.dev/media/pronunciations/en/dreamed-us.mp3', 'dreamt', NULL, 39);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/kɹiːp/', 0.000006152366, 'creep', 'https://api.dictionaryapi.dev/media/pronunciations/en/creep-us.mp3', 'crept', 'https://api.dictionaryapi.dev/media/pronunciations/en/crept-us.mp3', NULL, NULL, 'crept', 'https://api.dictionaryapi.dev/media/pronunciations/en/crept-us.mp3', NULL, NULL, 30);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈklɪŋ/', 0.000005280674, 'cling', NULL, 'clung', 'https://api.dictionaryapi.dev/media/pronunciations/en/clung-us.mp3', NULL, NULL, 'clung', 'https://api.dictionaryapi.dev/media/pronunciations/en/clung-us.mp3', NULL, NULL, 26);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/əˈweɪk/', 0.000004760366, 'awake', 'https://api.dictionaryapi.dev/media/pronunciations/en/awake-us.mp3', 'awakened', 'https://api.dictionaryapi.dev/media/pronunciations/en/awakened-us.mp3', 'awoke', NULL, 'awakened', 'https://api.dictionaryapi.dev/media/pronunciations/en/awakened-us.mp3', 'awoken', NULL, 4);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/əˈweɪk/', 0.000004760366, 'awake', 'https://api.dictionaryapi.dev/media/pronunciations/en/awake-us.mp3', 'awakened', 'https://api.dictionaryapi.dev/media/pronunciations/en/awakened-us.mp3', 'awoke', NULL, 'awakened', 'https://api.dictionaryapi.dev/media/pronunciations/en/awakened-us.mp3', 'awoken', NULL, 2);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/bɹiːd/', 0.000004234274, 'breed', 'https://api.dictionaryapi.dev/media/pronunciations/en/breed-us.mp3', 'bred', NULL, NULL, NULL, 'bred', NULL, NULL, NULL, 15);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈkləʊð/', 0.000003806850, 'clothe', 'https://api.dictionaryapi.dev/media/pronunciations/en/clothe-us.mp3', 'clothed', NULL, 'clad', 'https://api.dictionaryapi.dev/media/pronunciations/en/clad-uk.mp3', 'clothed', NULL, 'clad', 'https://api.dictionaryapi.dev/media/pronunciations/en/clad-uk.mp3', 27);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈdaɪv/', 0.000002560760, 'dive', NULL, 'dove', NULL, 'dived', NULL, 'dived', NULL, 'dived', NULL, 36);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈbliːd/', 0.000001687526, 'bleed', NULL, 'bled', NULL, NULL, NULL, 'bled', NULL, NULL, NULL, 12);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈbʌst/', 0.000001486595, 'bust', 'https://api.dictionaryapi.dev/media/pronunciations/en/bust-us.mp3', 'busted', NULL, 'bust', NULL, 'busted', NULL, 'bust', NULL, 21);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈdeɪdɹiːm/', 0.000000125977, 'daydream', NULL, 'daydreamed', NULL, 'daydreamt', NULL, 'daydreamed', NULL, 'daydreamt', NULL, 33);
INSERT INTO `verbs` (`phonetics`, `usageIndex`, `infinitive`, `infinitive_audio`, `simple_past`, `simple_past_audio`, `simple_past_uk`, `simple_past_uk_audio`, `participle`, `participle_audio`, `participle_uk`, `participle_uk_audio`, `id`) VALUES ('/ˈkɹɑːsˌbɹiːd/', 0.000000095648, 'crossbreed', NULL, 'crossbred', NULL, NULL, NULL, 'crossbred', NULL, NULL, NULL, 31);
